;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Advantage.STA",NewTagName="Advantage.CON")
+GameplayTagRedirects=(OldTagName="Disadvantage.STA",NewTagName="Disadvantage.CON")
+GameplayTagList=(Tag="Advantage",DevComment="")
+GameplayTagList=(Tag="Advantage.Acrobatics",DevComment="")
+GameplayTagList=(Tag="Advantage.AnimalHandling",DevComment="")
+GameplayTagList=(Tag="Advantage.Arcana",DevComment="")
+GameplayTagList=(Tag="Advantage.Athletics",DevComment="")
+GameplayTagList=(Tag="Advantage.Attack",DevComment="")
+GameplayTagList=(Tag="Advantage.Attack.Stealth",DevComment="")
+GameplayTagList=(Tag="Advantage.CHA",DevComment="")
+GameplayTagList=(Tag="Advantage.CON",DevComment="")
+GameplayTagList=(Tag="Advantage.Deception",DevComment="")
+GameplayTagList=(Tag="Advantage.DEX",DevComment="")
+GameplayTagList=(Tag="Advantage.History",DevComment="")
+GameplayTagList=(Tag="Advantage.Insight",DevComment="")
+GameplayTagList=(Tag="Advantage.INT",DevComment="")
+GameplayTagList=(Tag="Advantage.Intimidation",DevComment="")
+GameplayTagList=(Tag="Advantage.Investigation",DevComment="")
+GameplayTagList=(Tag="Advantage.Medicine",DevComment="")
+GameplayTagList=(Tag="Advantage.Nature",DevComment="")
+GameplayTagList=(Tag="Advantage.Perception",DevComment="")
+GameplayTagList=(Tag="Advantage.Performance",DevComment="")
+GameplayTagList=(Tag="Advantage.Persuasion",DevComment="")
+GameplayTagList=(Tag="Advantage.ReceiveAttack",DevComment="")
+GameplayTagList=(Tag="Advantage.ReceiveAttack.Blur",DevComment="")
+GameplayTagList=(Tag="Advantage.Religion",DevComment="")
+GameplayTagList=(Tag="Advantage.SleightOfHand",DevComment="")
+GameplayTagList=(Tag="Advantage.Stealth",DevComment="")
+GameplayTagList=(Tag="Advantage.STR",DevComment="")
+GameplayTagList=(Tag="Advantage.Survival",DevComment="")
+GameplayTagList=(Tag="Advantage.WIS",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Acrobatics",DevComment="")
+GameplayTagList=(Tag="Disadvantage.AnimalHandling",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Arcana",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Athletics",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Attack",DevComment="")
+GameplayTagList=(Tag="Disadvantage.CHA",DevComment="")
+GameplayTagList=(Tag="Disadvantage.CON",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Deception",DevComment="")
+GameplayTagList=(Tag="Disadvantage.DEX",DevComment="")
+GameplayTagList=(Tag="Disadvantage.History",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Insight",DevComment="")
+GameplayTagList=(Tag="Disadvantage.INT",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Intimidation",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Investigation",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Medicine",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Nature",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Perception",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Performance",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Persuasion",DevComment="")
+GameplayTagList=(Tag="Disadvantage.ReceiveAttack",DevComment="")
+GameplayTagList=(Tag="Disadvantage.ReceiveAttack.Stealth",DevComment="")
+GameplayTagList=(Tag="Disadvantage.ReceiveAttack.Stunned",DevComment="")
+GameplayTagList=(Tag="Disadvantage.ReceiveAttack.TrueStrike",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Religion",DevComment="")
+GameplayTagList=(Tag="Disadvantage.SleightOfHand",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Stealth",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Stealth.HeavyArmor",DevComment="")
+GameplayTagList=(Tag="Disadvantage.STR",DevComment="")
+GameplayTagList=(Tag="Disadvantage.Survival",DevComment="")
+GameplayTagList=(Tag="Disadvantage.WIS",DevComment="")
+GameplayTagList=(Tag="Ignore.OpportunityAttack",DevComment="")
+GameplayTagList=(Tag="Status.Stealth",DevComment="")
+GameplayTagList=(Tag="Status.Stunned",DevComment="")
+GameplayTagList=(Tag="Status.Stunned.Sleeping",DevComment="")

